# Generated by Django 2.1.2 on 2018-11-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(db_index=True, max_length=50)),
                ('is_strict', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('query', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('aspects', models.ManyToManyField(blank=True, to='refinements.Aspect')),
            ],
            options={
                'ordering': ['group', '-order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinements.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together={('group', 'slug')},
        ),
    ]
