# Generated by Django 2.2.10 on 2020-02-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_remove_authorization_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authorization',
        ),
    ]
